name: glances
adopt-info: glances
summary: Glances an Eye on your system. A top/htop alternative.
description: |
  Glances is a cross-platform monitoring tool which aims to present
  a maximum of information in a minimum of space through a curses or
  Web based interface. It can adapt dynamically the displayed information
  depending on the user interface size.

grade: stable
confinement: strict

apps:
  glances:
    command: bin/glances
    plugs:
      - network
      - system-observe
      - mount-observe
      - hardware-observe
      - log-observe
      - network-observe
      - physical-memory-observe
      - upower-observe
      - home
      - network-bind
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  glances:
    plugin: python
    source: .
    # FIXME: Theoretically this also replaces `summary` and `description`
    #        keys, however due to the following bug we still need to keep
    #        them until it is fixed.
    #        https://bugs.launchpad.net/snapcraft/+bug/1813364
    parse-info: [setup.py]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
        "$(git describe --always --dirty --tags --match 'v*' | sed s/^v//)"
  bottle:
    plugin: python
    source: https://github.com/bottlepy/bottle.git
    source-branch: release-0.12
    source-depth: 1
  docker:
    plugin: python
    source: https://github.com/docker/docker-py.git
    source-tag: '3.7.0'
    source-depth: 1
